catalyst: &catalyst
  symbols: [Fe, Fe, Fe, Fe, Fe, Fe, Fe, Fe]
  coordinates: [2.98605559e+00, 9.14289068e-01, 1.05573008e+00,
               2.98605559e+00, 2.74286720e+00, 1.05573008e+00,
               2.98605559e+00, 4.57144534e+00, 1.05573008e+00,
               1.49302780e+00, 1.82857814e+00, 5.27865040e-01,
               1.49302780e+00, 3.65715627e+00, 5.27865040e-01,
               0, 9.14289068e-01, 0,
               0, 2.74286720e+00, 0,
               0, 4.57144534e+00, 0]

steps:
  one:
    fixed:
      << : *catalyst
    react:
      symbols: [N, H, H]
      coordinates: [1, 3, 4]
    config:
      active_electrons: ${sum:1,1,7} # H + H + N
      active_orbitals: 1
      charge: 1
      basis: "STO-3G"
  two:
    fixed:
      symbols: ${concat:${catalyst.symbols}, ${steps.one.react.symbols}}
      coordinates: ${concat:${catalyst.coordinates}, ${last_element:${load_json:artifact,step1,coords.txt}}}
    react:
      symbols: [H, H]
      coordinates: [1,2,3]
    config:
      active_electrons: ${steps.one.config.active_electrons}
      active_orbitals: ${sum:1,1,1,1,3}  # (1s1) + (1s1) + (1s2 + 2s2 + 2p3)
      charge: 1
      basis: "STO-3G"
      optimization: "bo"

step_to_run: two