catalyst: &catalyst
  symbols: [Fe, Fe, Fe, Fe, Fe]
  coordinates: [1, 2, 3, 4, 5 ,6]

steps:
  one:
    fixed:
      << : *catalyst
    react:
      symbols: [N, H, H]
      coordinates: [1, 3, 4]
    config:
      active_electrons: 1
      active_orbitals: 1
      charge: 1
      basis: "STO-3G"
  two:
    fixed:
      symbols: ${concat:${catalyst.symbols}, ${steps.one.react.symbols}}
      coordinates: ${concat:${catalyst.coordinates}, ${last_element:${load_json:artifact,step1,coords.txt}}}
    react:
      symbols: [H, H]
      coordinates: [1,2,3]
    config:
      active_electrons: 1
      active_orbitals: 1
      charge: 1
      basis: "STO-3G"
